#!/bin/awk -f
BEGIN {
  FS="\t"
}
{
  date = $1
  desc = $2
  # Check which field has an amount in it, one is credit, one is debit
  if(match($3, "^£")) { # A dollar sign in the 8th field
    amount = $3
  } else {
    amount = "-" $4
  }

  # Convert date
  FS="[/ ]"
  $0=$0
  date = $3 "/" $2 "/" $1
  gsub("[ \t]", "", date) # Trim out all the whitespace
  FS="\t"

  printf("%.4d\t%s\t%s\t%s\n", NR, date, desc, amount);
}
